[package]
name = "symbios"
version = "1.0.1"
edition = "2024"
authors = ["Janus"]
description = "A derivation engine for L-Systems (ABOP compliant)."
license = "MIT"
readme = "README.md"
repository = "https://github.com/TheJanusStream/symbios"
keywords = ["lsystem", "procedural", "generative", "simulation", "no-std"]
categories = ["simulation", "game-development", "mathematics"]

[dependencies]
nom = "8.0.0"
rand = "0.9.2"
rand_pcg = "0.9.0"
thiserror = "2.0.17"
serde = { version = "1.0", features = ["derive", "rc"] }

[dev-dependencies]
serde_json = "1.0"
criterion = "0.5"

[[bench]]
name = "bench_main"
harness = false

[profile.bench]
debug = true
